CREATE TABLE [dbo].[Customer_Group] (
    [Cust_Group_Seq]       INT           NOT NULL,
    [Master_Cust_ID]       NVARCHAR (12) NOT NULL,
    [Branch_No]            NVARCHAR (8)  NOT NULL,
    [Division_No]          NVARCHAR (8)  NOT NULL,
    [Legal_Name]           NVARCHAR (35) NULL,
    [DBA]                  NVARCHAR (35) NULL,
    [EIN]                  NVARCHAR (35) NULL,
    [Billing_Address_1]    NVARCHAR (45) NULL,
    [Billing_Address_2]    NVARCHAR (45) NULL,
    [Billing_City]         NVARCHAR (45) NULL,
    [Billing_State]        NVARCHAR (42) NULL,
    [Billing_County]       NVARCHAR (42) NULL,
    [Billing_Country]      NVARCHAR (3)  NULL,
    [Billing_Zip]          NVARCHAR (10) NULL,
    [AP_Contact_Name]      NVARCHAR (30) NULL,
    [AP_Email]             NVARCHAR (30) NOT NULL,
    [AP_Phone]             NVARCHAR (15) NULL,
    [Main_Phone]           NVARCHAR (15) NULL,
    [Main_Fax]             NVARCHAR (15) NULL,
    [Website]              NVARCHAR (45) NULL,
    [Corp_Address_1]       NVARCHAR (45) NULL,
    [Corp_Address_2]       NVARCHAR (45) NULL,
    [Corp_City]            NVARCHAR (25) NULL,
    [Corp_State]           NVARCHAR (2)  NULL,
    [Corp_County]          NVARCHAR (25) NULL,
    [Corp_Country]         NVARCHAR (3)  NULL,
    [Corp_Zip]             NVARCHAR (10) NULL,
    [Master_Account_Owner] NVARCHAR (10) NULL,
    [Lead_Source]          NVARCHAR (45) NULL,
    CONSTRAINT [PK_Master_Customer_1] PRIMARY KEY CLUSTERED ([Cust_Group_Seq] ASC)
);

