CREATE TABLE [dbo].[Daily_Transaction] (
    [Daily_Transaction_Seq_ID] INT        NOT NULL,
    [Asset_Seq_ID]             INT        NULL,
    [Asset_ID]                 NCHAR (10) NULL,
    [Cust_ID]                  NCHAR (10) NULL,
    [Device_MAC]               NCHAR (10) NULL,
    [Device_group_1]           NCHAR (10) NULL,
    [Date/Time]                NCHAR (10) NULL,
    [Measurement_Type1]        NCHAR (10) NULL,
    [Measurement_Count_1]      NCHAR (10) NULL,
    [Measurement_Ave_1]        NCHAR (10) NULL,
    [Measurement_Min_Value_1]  NCHAR (10) NULL,
    [Measurement_Max_Value_1]  NCHAR (10) NULL,
    [Measurement_Type2]        NCHAR (10) NULL,
    [Measurement_Count_2]      NCHAR (10) NULL,
    [Measurement_Ave_2]        NCHAR (10) NULL,
    [Measurement_Min_Value_2]  NCHAR (10) NULL,
    [Measurement_Max_Value_2]  NCHAR (10) NULL,
    [Measurement_Type3]        NCHAR (10) NULL,
    [Measurement_Count_3]      NCHAR (10) NULL,
    [Measurement_Ave_3]        NCHAR (10) NULL,
    [Measurement_Min_Value_3]  NCHAR (10) NULL,
    [Measurement_Max_Value_3]  NCHAR (10) NULL,
    CONSTRAINT [PK_Daily_Transaction] PRIMARY KEY CLUSTERED ([Daily_Transaction_Seq_ID] ASC),
    CONSTRAINT [FK_Daily_Transaction_Asset] FOREIGN KEY ([Asset_Seq_ID]) REFERENCES [dbo].[Asset] ([Asset_Seq_ID])
);

