CREATE TABLE [dbo].[Invoices] (
    [Invoices_Seq_ID]      INT        NOT NULL,
    [Invoice_No]           NCHAR (10) NULL,
    [Order_Date]           NCHAR (10) NULL,
    [Invoice_Date]         NCHAR (10) NULL,
    [Type]                 NCHAR (10) NULL,
    [Cust_ID]              NCHAR (10) NULL,
    [Cust_Seq_ID]          INT        NULL,
    [Customer_Name]        NCHAR (10) NULL,
    [Customer_Contact]     NCHAR (10) NULL,
    [Customer_Email]       NCHAR (10) NULL,
    [Customer_Phone]       NCHAR (10) NULL,
    [Customer_Mob]         NCHAR (10) NULL,
    [Related_PO]           NCHAR (10) NULL,
    [Special_Instructions] NCHAR (10) NULL,
    [Tax_Exempt]           NCHAR (10) NULL,
    [Invoice_Pmt_Terms]    NCHAR (10) NULL,
    [BOSS_Sales_Team_1]    NCHAR (10) NULL,
    [BOSS_Sales_Team_2]    NCHAR (10) NULL,
    [Contractor_ID]        NCHAR (10) NULL,
    [Invoice_Address_1]    NCHAR (10) NULL,
    [Invoice_Address_2]    NCHAR (10) NULL,
    [Invoice_City]         NCHAR (10) NULL,
    [Invoice_State]        NCHAR (10) NULL,
    [Invoice_County]       NCHAR (10) NULL,
    [Invoice_Zip]          NCHAR (10) NULL,
    [Invoice_Country]      NCHAR (10) NULL,
    [Invoice_Attention]    NCHAR (10) NULL,
    [Shipping_Address_1]   NCHAR (10) NULL,
    [Shipping_Address_2]   NCHAR (10) NULL,
    [Shipping_City]        NCHAR (10) NULL,
    [Shipping_State]       NCHAR (10) NULL,
    [Shipping_County]      NCHAR (10) NULL,
    [Shipping_Zip]         NCHAR (10) NULL,
    [Shipping_Country]     NCHAR (10) NULL,
    [Shipping_Attention]   NCHAR (10) NULL,
    [Currency]             NCHAR (10) NULL,
    [Sub_Total]            NCHAR (10) NULL,
    [Sales_Tax_Total]      NCHAR (10) NULL,
    [Payment_Credit]       NCHAR (10) NULL,
    [Amount_due]           NCHAR (10) NULL,
    CONSTRAINT [PK_Invoices] PRIMARY KEY CLUSTERED ([Invoices_Seq_ID] ASC)
);

